name: 'Setup QEMU'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable
      if: runner.os == 'Linux' || runner.os == 'macOS'
    - if: runner.os == 'Linux' || runner.os == 'macOS'
      shell: bash
      run: |
        export NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1
        nix-channel --add https://nixos.org/channels/nixpkgs-unstable unstable
        nix-channel --update
        nix-env -iA qemu_full -f '<nixpkgs>'

    - if: runner.os == 'Windows'
      shell: pwsh
      run: |
        choco install qemu --ignore-checksums
        echo "C:\Program Files\qemu" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
