name: 'Setup QEMU'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: Homebrew/actions/setup-homebrew@master
      if: runner.os == 'Linux'

    - if: runner.os == 'Linux'
      shell: bash
      run: brew update && brew install qemu

    - if: runner.os == 'macOS'
      shell: bash
      run: brew update && brew install qemu

    - if: runner.os == 'Windows'
      shell: bash
      run: |
        scoop install qemu

