name: 'Setup QEMU'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt install -y qemu qemu-system || sudo apt update && sudo apt install -y qemu qemu-system

    - if: runner.os == 'macOS'
      shell: bash
      run: |
        brew update
        brew list qemu || brew install qemu

    - if: runner.os == 'Windows'
      shell: pwsh
      run: |
        choco install qemu --ignore-checksums
        echo "C:\Program Files\qemu" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
